### ISSUE TITLE
Broken Link: Custom KnowledgeBase Documentation

### ISSUE THREAD

**Issue by arashbagherabadi** [wallet-maker/cytopus#17]
Hello,

I noticed that the link provided for “Retrieve custom KnowledgeBase (documentation to build KnowledgeBase object here)” is not working. This link is intended to guide users on how to build a KnowledgeBase object, but it currently leads to a non-existent page.

Could you please update the link or provide the correct URL to the documentation?

Thank you.

**Comment by wallet-maker** [comment]
sorry for this glitch! 
This is the notebook: https://github.com/wallet-maker/cytopus/blob/main/notebooks/KnowledgeBase_construct.ipynb

link should work now too!

**Comment by arashabadi** [comment]
I appreciate that. This link works. 

FYI, I am still facing "404 - page not found" in your README!

https://github.com/wallet-maker/cytopus/blob/Cytopus_1.3/notebooks/KnowledgeBase_construct.ipynb
